### DISCUSSION TITLE
CI/CD pipelines use unmaintained actions

### DISCUSSION THREAD

**Discussion by tessus** [orhun/rustypaste#115] [General]
I just wanted to point out that the CI and CD pipelines use unmaintained actions.

The `actions-rs/*` actions are no longer maintained. The solution is to replace them with:

```
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
```

By default a minimal toolchain will be installed. But one can add components as a comma-separated list: `rustfmt, clippy, ...`

**Comment by orhun** [comment]
It would be nice to replace them with dtolnay's action but I had some problems with it in the past: https://github.com/dtolnay/rust-toolchain/issues/83

**Reply by tessus** [reply]
Hmm, but what I can ascertain this was an issue with rustup. So I don't understand how action-rs/toolchain could have worked in this situation since it is also using rustup.

In regards to cargo, it is installed with the toolchain so there is no reason to use the unmaintained cargo action. Why not use it like this:

```
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Check the formatting
        run: cargo fmt --all -- --check --verbose
      - name: Check the lints
        run: cargo clippy --lib --tests --bins --examples --verbose -- -D warnings
```

Here is my pipeline: https://github.com/tessus/uts2ts/blob/master/.github/workflows/ci.yml
